version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: myapp
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myapp"]
      interval: 5s
      retries: 5

  migrate:
    image: migrate/migrate:v4.17.2
    profiles: ["tools"]   # `docker compose --profile tools run migrate ...`
    entrypoint: ["migrate", "-path", "/migrations", "-database", "postgres://myapp:myapp@db:5432/myapp?sslmode=disable"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=myapp
      - DB_PASSWORD=myapp
      - DB_NAME=myapp
